apiVersion: 1
contactPoints:
    - orgId: 1
      name: samana-slack
      receivers:
        - uid: ce7ed779-a88d-4ac4-9f46-2d767eaaa669
          type: slack
          settings:
            recipient: alerts-mmm
            token: xxx
          disableResolveMessage: false
